import Head from 'next/head'
import { FC } from 'react'

const HomPage: FC = () => {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-2xl text-gray-800 font-bold">Hello World !</h1>
      </main>
    </div>
  )
}

export default HomPage
